apiVersion: v1
kind: Service
metadata:
  name: nginx-java-service-external
spec:
  selector:
    app: nginx-java
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
